#!/bin/bash

#php artisan optimize --force
composer dumpautoload -o

php artisan config:clear && php artisan config:cache
php artisan route:clear && php artisan route:cache
php artisan view:clear && php artisan view:cache
php artisan cache:clear

[ -L public/storage ] && unlink public/storage && php artisan storage:link
